### PR TITLE
Add core structure

### PR DESCRIPTION
**Pull request by samuelloza**
I add the next tree directory

image

### CODE REVIEW

**Comment by MirkoFer-622** [comment]
I think that utils directory should be under core, because utils could be reused at another project. Could you change it please?

**Review by MirkoFer-622 — CHANGES_REQUESTED** [review]
I think that utils directory should be under core, because utils could be reused at another project. Could you change it please?

**Comment by samuelloza** [comment]
> I think that utils directory should be under core

I think utils is necessary for not repeat code for example we can have readerJson or readerFileGradle

**Comment by MirkoFer-622** [comment]
> > I think that utils directory should be under core
> 
> I think utils is necessary for not repeat code for example we can have readerJson or readerFileGradle

You have the reason, so it should be in core directory, and not out of there, utils could be reused  in any project and not only for salesforce. This Is the reason for put utils inside core directory.

**Pull request merged**
